### ISSUE TITLE
[Feature Request] Option to disable sensors

### ISSUE THREAD

**Issue by cameronkelley** [MesserschmittX/lovelace-nicehash-excavator-monitor-card#2]
It would be great if there was an option to disable some sensors from displaying. I only have a single card in my system and have other means of monitoring CPU and RAM usage. In my case, the following sensors are unnecessary.

Covered by other integrations:
* CPU
* RAM

Unnecessary with single card system:
* Overall hash rate
* Overall power 
* ID
* Model
* Vendor

**Comment by NeonGrayX** [comment]
I already wanted to do that, it's now in release 0.1.2

**Comment by cameronkelley** [comment]
> I already wanted to do that, it's now in release 0.1.2

Thanks a lot!
